// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import goerror "github.com/devit-tel/goerror"
import mock "github.com/stretchr/testify/mock"

import staff "github.com/afternoob/gogo-boilerplate/domain/staff"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Get provides a mock function with given fields: staffId
func (_m *Repository) Get(staffId string) (*staff.Staff, goerror.Error) {
	ret := _m.Called(staffId)

	var r0 *staff.Staff
	if rf, ok := ret.Get(0).(func(string) *staff.Staff); ok {
		r0 = rf(staffId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*staff.Staff)
		}
	}

	var r1 goerror.Error
	if rf, ok := ret.Get(1).(func(string) goerror.Error); ok {
		r1 = rf(staffId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(goerror.Error)
		}
	}

	return r0, r1
}

// GetUsersByCompany provides a mock function with given fields: companyId, offset, limit
func (_m *Repository) GetUsersByCompany(companyId string, offset int, limit int) ([]*staff.Staff, goerror.Error) {
	ret := _m.Called(companyId, offset, limit)

	var r0 []*staff.Staff
	if rf, ok := ret.Get(0).(func(string, int, int) []*staff.Staff); ok {
		r0 = rf(companyId, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*staff.Staff)
		}
	}

	var r1 goerror.Error
	if rf, ok := ret.Get(1).(func(string, int, int) goerror.Error); ok {
		r1 = rf(companyId, offset, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(goerror.Error)
		}
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *Repository) Save(_a0 *staff.Staff) goerror.Error {
	ret := _m.Called(_a0)

	var r0 goerror.Error
	if rf, ok := ret.Get(0).(func(*staff.Staff) goerror.Error); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goerror.Error)
		}
	}

	return r0
}
